### PR TITLE
Release `v0.3.0` - New backend, Authentication, and New Validation

### PR DESCRIPTION
**Pull request by nleroy917**
This new release includes a lot of changes, namely the migration to a new backend `pepdbagent`. PEPhub is now backed by a postgres database that stores the PEPs for fast retrieval and scalable storage. This increase in complexity required a companion package to be built called [`pepingester`](https://github.com/pepkit/pepingester) which will take a PEP of PEPs (a POP) and insert them into a database for use with `pephub`.

### CODE REVIEW

**Comment by nsheff** [comment]
I think you need to add to requires: `pyjwt[crypto]`

**Comment by nleroy917** [comment]
> I think you need to add to requires: pyjwt[crypto]

When I went to install that locally, `pip` told me it couldn't find it. `pyjwt`, however, was found.

**Comment by nsheff** [comment]
Hmm. See: https://pyjwt.readthedocs.io/en/latest/installation.html

**Comment by nleroy917** [comment]
I've got both `cryptography` and `pyjwt` in the reqs. So, we should be okay?

**Comment by nsheff** [comment]
See above :)

> The pyjwt[crypto] format is recommended in requirements files in projects using PyJWT, as a separate cryptography requirement line may later be mistaken for an unused requirement and removed.

**Comment by nleroy917** [comment]
It's `zsh` that is messing up the installation. It uses square brackets for pattern matching. So `pyjwt[crpyto]` should be fine in bash. I'll change the file.

**Comment by nleroy917** [comment]
Requirements are updated now and pointing at released versions of `pepdbagent` and `peppy`. I think we might be good to go.

**Pull request merged**
