### PR TITLE
Conversion Endpoints and more

### PR DESCRIPTION
**Pull request by nleroy917**
Using the new `eido` stuff I added, I was able to move forward and add some conversion endpoints.

**Example:**
```
GET /eido/filters -> returns available filters
GET /pep/demo/BiocProject/convert?filter=<filter> -> returns conversion
```

If you pass no filter it defaults to `basic`. I also included checking for valid filter names. Since the eido changes weren't merged and released, I am pointing my development environment at my fork of eido that has these changes implemented. So, before this is merged, i'd need to change back to the original eido.

Before merge:
- [x] wait for https://github.com/pepkit/eido/pull/32
- [x] update this to require and use new released version of eido
- [x] update version/changelog

### CODE REVIEW

**Comment by nleroy917** [comment]
I think this can be merged soon -- we need to wait for `eido` to be merged + released which needs `peppy v0.32.0` to be merged and released. I have been testing this with the development peppy and it seems stable (it even seems faster).

**Comment by nsheff** [comment]
This sounds great!

**Comment by nleroy917** [comment]
Should we also wait for a merge of my PR on eido (https://github.com/pepkit/eido/pull/38) Since this contains the code to return conversion results.

**Comment by nsheff** [comment]
> Should we also wait for a merge of my PR on eido ([pepkit/eido#38](https://github.com/pepkit/eido/pull/38)) Since this contains the code to return conversion results.

Just for reference, It's best to edit  this kind of thing in as TODO checkbox items in the first post, so that it's clear that the merge should wait on this (as opposed to having to read through all the comments to see if there are any TODOs remaining).

**Comment by nleroy917** [comment]
This PR also fixes/addresss:

#25 
#26 
#23 
#28

**Comment by nleroy917** [comment]
I think I have addressed everything that we discussed Friday.

**issues addressed and/or fixed in this PR:**
#22 (implement conversion endpoints)
#25 (project endpoint case-sensitivity)
#26 (don't open demo links in new window)
#23 (dotfile standardization -> change to `.pep.yaml`)
#28 (splash page styling)
#29 (pinned version reqs)
#27 (remove `_project` representation on endpoints)

**Pull request merged**
