### PR TITLE
Integrate views into the user interface

### PR DESCRIPTION
**Pull request by nleroy917**
## Overview
This PR integrates the views API into the actual user interface of PEPhub. Its quite simple and provides a dropdown where users can select a view to replace the sample table instead of viewing the entire thing. Moreover, it adds functionality to only pull the sample table if the project annotation indicates that the sample able is less than some maximum value (`5,000` right now).

If this threshold is broken, it displays a warning to the user telling them to select a view instead.

## Relevant issues
- #274 
- #289 

## Screnshots
**Warning popup:**

**View selector:**
<div>
image
</div>

### TODO:
- [x] bump version
- [x] changelog

### CODE REVIEW

**Comment by nleroy917** [comment]
@khoroshevskyi anything else?

**Comment by nleroy917** [comment]
Still investigating some weirdness with the way that the network requests hang for `config`, `subsamples`, and `views`

**Comment by khoroshevskyi** [comment]
It seems like `Save` button is available in the views, and I can modify sample table
image

---

+ Project >5K is not disable yet

**Comment by khoroshevskyi** [comment]
> Still investigating some weirdness with the way that the network requests hang for `config`, `subsamples`, and `views`

This problem can be realted to this issue: https://github.com/pepkit/pepdbagent/issues/128

**Review by khoroshevskyi — CHANGES_REQUESTED** [review]
LGTM, but still needs a little bit of polishing:
- [x] Disable `save` button and modification of sample table
- [x] Disable loading of huge projects

**Comment by nleroy917** [comment]
> This problem can be realted to this issue: [pepkit/pepdbagent#128](https://github.com/pepkit/pepdbagent/issues/128)

Close, but no. It's the validation that's causing issues. Validating that sample table takes a really long time, so I need to make sure to run that only if the project has less than 5,000 samples

**Comment by nleroy917** [comment]
### feedback from infrastructure meeting
Instead of a popup, just replace the sample table with a message that says its not going to display the sample table, and tell you to set the view at the top to see samples

**Comment by khoroshevskyi** [comment]
User feedback (not from me):
- Views are confusing, we should add information what is that (something like info button)
- Description of the each view is missing (it is one of the annotations). `pepdbagent.views.get_annotation(...)`
- User is confused how to create a new view table. This information also should be added to info button.
- If it would be possible to create a new view it would be more usefull. And overall it is a cool feature.
The best solution for that would be an additional window (something like create new pop) where you would create new view (but this is low priority) 

>> MOST important: add info about that, how to modify it

+ NONE should be changed to default or something else, because it seems that this project is lack of something

**Comment by nleroy917** [comment]
> Description of the each view is missing (it is one of the annotations). pepdbagent.views.get_annotation(...)

I agree this is ideal, but real estate is getting cramped up there already... what sort of UI component could we render that adds a description while not making it too large? I could add it to the "More" dropdown and make it a modal

**Review by khoroshevskyi — APPROVED** [review]
Looks very professional

**Pull request merged**
