### PR TITLE
Merge`v0.6.0` into `dev`

### PR DESCRIPTION
**Pull request by nleroy917**
### Todo:
- [x] Update version
- [x] Update change log

### In this update:
 - [x] #64 
 - [x] #94 
 - [x] #96 
 - [x] #97 
 - [x] #102 
 - [x] #99 
 - [x] #85 
 - [x] #57 
 - [x] #104 
 - [x] #105 

I mostly address things like **polishing**, **new authentication flow**, **creating PEPs more easily**, **bug fixing + stability**, and **performance**.

### CODE REVIEW

**Comment by khoroshevskyi** [comment]
Errors: 
- [x] can't open private projects. I can see this private in the list of my projects and  edit it, but I can't open it. 
image

- [x] Validation is failing in simplest files. Error message in console:

```
Traceback (most recent call last):
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/bnt4me/virginia/venv/pephub/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/bnt4me/virginia/repos/pephub/./pephub/routers/eido/eido.py", line 248, in validate_raw
    project_config_dict["sample_table"] = "sample_table.csv"
TypeError: 'str' object does not support item assignment
```

---

I didn't test everything, especially search. I will test it soon

**Comment by nleroy917** [comment]
>  Validation is failing in simplest files. Error message in console:

can you tell me which one? I can't reproduce this.

**Comment by khoroshevskyi** [comment]
> > Validation is failing in simplest files. Error message in console:
> 
> can you tell me which one? I can't reproduce this.

e.g. http://localhost:8000/Khoroshevskyi/new1?tag=new1
This is sample that was created using: Submit a new PEP/new

**Comment by nleroy917** [comment]
### Notes from meeting 03/07/2023
- ~~Remove "Number of results" on search~~ Done.
- ~~Make changes to authentication to support `code` flow~~ Done.
  - ~~Add some documentation for this so people can write `cli`'s and `SPA`s~~ Done.
- ~~Try to finish up those last lingering bugs~~
- ~~"Create" not "New"~~ Done.

**Comment by nleroy917** [comment]
@Khoroshevskyi I want to merge this ASAP... do you have a reproducible example of your issue yet so I can bug fix? If not I will merge this soon.

**Comment by khoroshevskyi** [comment]
> @Khoroshevskyi I want to merge this ASAP... do you have a reproducible example of your issue yet so I can bug fix? If not I will merge this soon.

Reproducible example: 
1) Create new project
2) Validate it

+ after your new changes I am getting new error, so I can't even start pophub: 
image

**Comment by nleroy917** [comment]
Make sure you pull again.. that error you are seeing should have been fixed

**Pull request merged**
