### PR TITLE
Hot fix for subsample list with history changes (#379)

### LINKED ISSUE #379: Trying to view subsamples while in history mode causes error
To replicate: open a project with no subsamples and go into history view. Attempt to view the subsamples tab. Or, open a project and go to the subsamples tab. Attempt to go into history view. The page will crash.

I guess the solution for now is to disable the subsamples tab if in history mode, and if in the subsamples tab when entering history mode, go to samples tab?

### PR DESCRIPTION
**Pull request by nleroy917**
Simple one-line hot fix that resolves #379

### CODE REVIEW

**Comment by nleroy917** [comment]
Looks like some direct pushes to master got pulled in, but not relevant right now

**Comment by sanghoonio** [comment]
@khoroshevskyi @nleroy917 So in dev you can now view the subsample table in history mode, but the API seems to return only the current subsampletable data regardless of the history ID. Is this intended behavior?

**Comment by nleroy917** [comment]
That might be a question for Alex but if you don't have any changes to the sub sample table... wouldn't it return none?

**Comment by khoroshevskyi** [comment]
No, we didn't implement it,  for keeping history of subsamples we needed more time and restructuring

**Pull request merged**
