### PR TITLE
Replace UI with a React SPA

### PR DESCRIPTION
**Pull request by nleroy917**
## Overview
It seems like there is continual discussion around switching out the current user interface for a React SPA. I have spent some time setting up a minimal working example. There might be some oddities still, but just testing locally, it works for me.

## Instructions for running
You should be able to run the project in two steps: First, build the interface. Second, run the server. To build the interface you can navigate to the `web/` folder, and execute `npm install && npm build`. This should create a `dist/` folder in the same directory.

Next, return to the root of the project and simply run: `uvicorn pephub.main:app --reload`.

## Technical details
Server a React SPA that includes client-side routing off of FastAPI is not very trivial, however through some clever middleware, we can get it to work quite nicely. Switching to a react-based frontend comes with some nice features and some changes to the process of web development. I can detail these out very intricately if needed in the future

### CODE REVIEW

**Comment by khoroshevskyi** [comment]
🤔🤔🤔
image

**Comment by nleroy917** [comment]
I said "working example", not "complete rebuild" 😄

**Comment by nleroy917** [comment]
This is close... with sufficient testing and a majority opinion we can merge and swap out the old UI for the pure-react SPA

**Comment by khoroshevskyi** [comment]
Can you pull my changes to your branch and make sure every endpoint is working?

**Pull request merged**
