### PR TITLE
Release v0.10.4

### PR DESCRIPTION
**Pull request by khoroshevskyi**
Fixed zip downloading

### CODE REVIEW

**Review by nleroy917 — APPROVED** [review]
Nice. This looks good. Was it just something with a `peppy` change/incompatibility?

**Comment by khoroshevskyi** [comment]
> Was it just something with a `peppy` change/incompatibility?

Yes, because peppy doesn't have attmapp anymore

**Comment by nleroy917** [comment]
Makes sense

**Comment by nleroy917** [comment]
Thanks for jumping on this so fast.

**Pull request merged**
