### PR TITLE
Create splash page -- move things around

### PR DESCRIPTION
**Pull request by nleroy917**
Did a lot here...

I created a splash page and I moved some files around to facilitate the landing screen.

### CODE REVIEW

**Comment by nsheff** [comment]
can you resolve merge conflicts?

**Comment by nleroy917** [comment]
Should be good now. Was just a requirement.

**Comment by nsheff** [comment]
can you include something about the validator?

**Comment by nsheff** [comment]
can you upgrade to bootstrap 5 ? ('m starting to use bootstrap 5 for everything, it would be good to stay consistent)

**Review by nsheff — CHANGES_REQUESTED** [review]
- [x] use bootstrap 5
- [x] should we standardize on a lab tool template? (eg http://seqcolapi.databio.org/)? 
- [x] Is this using react? what for?
- [x] use the pep logo for the specification, not for pephub
- [x] let's invent a logo for pephub
- [x] replace filler splash text
- [x] search is broken: if you type 'demo' hit search, then update it, it updates all those endpoints...
- [x] learn more link goes to github?
- [x] can't search for changlab but it shows up in the pep-list endpoint
- [x] instead of try out the API, why not just include some examples?  I'm not sure I get the vision of this search box.
- [x] let's  stylize as either 'pephub' or 'PEPHub' over 'PepHub' I get the analogy to GitHub, but PEP is an acronym so "Pep" is weird.
- [x] needs a link to the validator

**Comment by nleroy917** [comment]
> should we standardize on a lab tool template? (eg http://refgenomes.databio.org/, http://seqcolapi.databio.org/)?

Sure that might make things easier. Do you have a link to that HTML?

>Is this using react? what for?

Yes, but only the search box. It was just the fastest way I knew how to quickly get an SPA-like functionality going...

>instead of try out the API, why not just include some examples? I'm not sure I get the vision of this search box.

Sure this is easier to implement too.

**Comment by nsheff** [comment]
> Sure this is easier to implement too.

Better yet -- can we also put real examples into the fastAPI docs? you can see how to do that for example here: 

http://seqcolapi.databio.org/docs#/

here's some code that populates that openapi with an example: 

https://github.com/refgenie/seqcolapi/blob/d0f77790e0eab71b5f45b24016b002ea7460a2a5/seqcolapi/main.py#L304

**Comment by nsheff** [comment]
Hi @nleroy917 how close are we to finishing off this PR?

**Comment by nleroy917** [comment]
If I can get the mounting to function properly then it's just adding the rest of the endpoints.

To be more specific... This is what I see when I hit the landing page (note the logo in the navbar):
image

However, hitting the `eido/validator` endpoint yields this:
image

So, something is weird with the static file mounting and FastAPI, an issue I have yet to resolve. I can ignore it for now if we want and just continue on.

**Comment by nleroy917** [comment]
I added (almost all) the endpoints we mentioned in #17. They should be functional. We still have all "API" type routes at the `/pep/` endpoints.

The landing page works, it just can't load the assets. I also added more examples on the landing page.

**Comment by nsheff** [comment]
Can you populate the Swagger docs with examples?

See this comment: https://github.com/pepkit/pephub/pull/14#issuecomment-985175441

**Comment by nsheff** [comment]
There used to be an endpoint that listed the availble PEPs, or namespaces. That was very nice, what happened to it?

**Comment by nleroy917** [comment]
I got rid of it -- not sure why... I can add it back. Is `/pep-list/` ok? Or is there a better name for it than that.

**Comment by nleroy917** [comment]
I'm looking at the [FastAPI docs](https://fastapi.tiangolo.com/tutorial/schema-extra-example/) and I can't see how to add examples to `GET` endpoints... With the seqcol example you provided... I see there is a default key-value in the function defined there, but I don't know if we want default values for namespaces

**Comment by nsheff** [comment]
> I'm looking at the [FastAPI docs](https://fastapi.tiangolo.com/tutorial/schema-extra-example/) and I can't see how to add examples to `GET` endpoints... With the seqcol example you provided... I see there is a default key-value in the function defined there, but I don't know if we want default values for namespaces

That's how you provide examples, those aren't defaults. The seqcol example shows you how to do it.

Here's the docs: https://fastapi.tiangolo.com/tutorial/schema-extra-example/

**Comment by nsheff** [comment]
I think once you have some demo examples, this looks good for a first release.

Then we can start to tweak what the endpoints actually serve, which I think right now is sub-optimal.

**Review by nsheff — APPROVED** [review]

**Comment by nleroy917** [comment]
Ok. I see the example now and the documentation. Maybe I am missing something, but I still can't get the `/docs` to populate with examples...

This is the code for the `/namespace` route:

```python
# examples
from ..route_examples import (
    example_namespace
)

router = APIRouter(
    prefix="/pep/{namespace}",
    dependencies=[Depends(verify_namespace)],
    tags=["namespace"],
)

@router.get("/", summary="Fetch details about a particular namespace.")
async def get_namespace(namespace: str = example_namespace):
    """
        Fetch namespace. Returns a JSON representation of the namespace and the projects inside it.
    """
    return JSONResponse(content=_PEP_STORES[namespace])
```

And this is the code for `example_namespace`:

```python
# example for /pep/{namespace}
example_namespace = Path(
    ...,
    description="A pep namespace.",
    example="demo",
)
```

I will push my code for this too.

**Comment by nsheff** [comment]
I think you will just need to follow the example. maybe get a minimal working example first to learn how the examples work and then try adapting it to the more complex case.

**Comment by nsheff** [comment]
Hey, are you planning to finish this off?

**Comment by nleroy917** [comment]
Yes. I left it just before Christmas trying to get examples to work. They still don't want to work... Any ideas? I've defined an example for the `/pep/{namespace}` endpoint like so:

```python
# pephub/route_examples.py
example_namespace = Path(
    ...,
    description="A namespace that holds projects.",
    regex=r"^\w+$",
    example="demo",
)
```

It is passed to the route definition:

```python
# pephub/routers/namespace.py
from ..route_examples import (
    example_namespace
)

router = APIRouter(
    prefix="/pep/{namespace}",
    dependencies=[Depends(verify_namespace)],
    tags=["namespace"],
)

@router.get("/", summary="Fetch details about a particular namespace.")
async def get_namespace(namespace: str = example_namespace):
    """Fetch namespace. Returns a JSON representation of the namespace and the projects inside it."""
    return JSONResponse(content=_PEP_STORES[namespace])
```

And then when visiting `/docs` I get... nothing...

image

I can't see how I am doing anything different than what's being done in the [sqlcolapi](https://github.com/refgenie/seqcolapi/blob/d0f77790e0eab71b5f45b24016b002ea7460a2a5/seqcolapi/main.py#L304)... **and** if I add constraints like `max_length` and `min_length` to the `pephub` example... the API will honor those and throw errors if I attempt to access a namespace with say, a character limit of 5 when a `min_length` of 10 is set. So, it seems to be fine other than the examples...

**Comment by nleroy917** [comment]
Upgrading to FastAPI from `0.70.0` to `0.71.0` did not fix the issue. I might open an issue with the FastAPI devs.

**Comment by nleroy917** [comment]
I'm inclined to merge + close this and open an issue for the examples problem, that way we can release and continue.

**Comment by nsheff** [comment]
The problem is in this line:

```
    dependencies=[Depends(verify_namespace)],
```

if you remove that line, your examples work. Can you double-check this dependency verification thing? I actually don't even know what that does.

**Comment by nleroy917** [comment]
It ensures that the namespace exists prior to executing the route logic. But that's interesting that the dependency injection seems to prevent your ability to declare an example in your request. [These](https://fastapi.tiangolo.com/tutorial/dependencies/) are the docs for dependencies. It seems like if you want a request parameter to be verified... you can't give it an example.

**Pull request merged**
